### ISSUE TITLE
Build issue on MAC OS

### ISSUE THREAD

**Issue by runk** [rlidwka/node-fann#11]
Hi there! I've encountered an issue with installing your module. `fann` lib is installed via macports, and header files placed to `/opt/local/include`. It looks like that gyp isn't aware of it and reports about error:

```
$ npm install fann

> fann@0.2.2 install /whatever/node_modules/fann
> node-gyp rebuild

  CXX(target) Release/obj.target/fann/src/fann-accs.o
In file included from ../src/fann-accs.cc:7:
In file included from ../src/node-fann.h:5:
../src/node-futil.h:7:10: fatal error: 'doublefann.h' file not found
#include <doublefann.h>
         ^
1 error generated.
make: *** [Release/obj.target/fann/src/fann-accs.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/homedir/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 13.0.0
gyp ERR! command "node" "/homedir/.nvm/v0.10.21/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /whatever/node_modules/fann
gyp ERR! node -v v0.10.21
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok
npm ERR! weird error 1
npm ERR! not ok code 0
```

```
$ file /opt/local/include/doublefann.h
/opt/local/include/doublefann.h: ASCII c program text
```

Any ideas how to fix it?

**Comment by leizongmin** [comment]
I met the same problem. Installed `fann` lib from `$ brew install fann`, but the include dir and library dir is under `/usr/local` not `/opt/local`

**Comment by fdelia** [comment]
Had the same issue: The paths in `binding.gyp` are wrong for mac. It worked for me after changing the paths `/opt/local/include` to `/usr/local/include` and `/opt/local/lib` to `/usr/local/lib`.
