### ISSUE TITLE
node 0.12.2: Module did not self-register.

### ISSUE THREAD

**Issue by joernroeder** [rlidwka/node-fann#22]
I'm testing node-fann inside the [aooj/fann docker image](https://registry.hub.docker.com/u/aooj/fann/dockerfile/) and it works well with the preinstalled node v0.10.26 and node-fann v1.0.0. But after I've [updated](https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories#installing-node-js-v0-12) node to the latest version 0.12.2 the following error occurred:

```
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/node_modules/fann/index.js:1:80)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by joernroeder** [comment]
ah! i've reinstalled `node-fann` after the node update and now it's working again. sorry for the issue…

**Comment by rlidwka** [comment]
Yep, when you update between node.js/io.js versions, you usually have to recompile native modules to work with that particular version you're using.

You can also run `npm rebuild` to recompile them instead of reinstalling.
