### ISSUE TITLE
can't install - log attached

### ISSUE THREAD

**Issue by drowne** [rlidwka/node-fann#29]
272 verbose stack Error: fann@1.0.0 install: `node-gyp rebuild`
272 verbose stack Exit status 1
272 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
272 verbose stack     at emitTwo (events.js:106:13)
272 verbose stack     at EventEmitter.emit (events.js:191:7)
272 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
272 verbose stack     at emitTwo (events.js:106:13)
272 verbose stack     at ChildProcess.emit (events.js:191:7)
272 verbose stack     at maybeClose (internal/child_process.js:877:16)
272 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
273 verbose pkgid fann@1.0.0
274 verbose cwd /Users/drowne/projects/nn_mastering
275 error Darwin 15.6.0
276 error argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "install" "fann"
277 error node v6.6.0
278 error npm  v3.10.7
279 error code ELIFECYCLE
280 error fann@1.0.0 install: `node-gyp rebuild`
280 error Exit status 1
281 error Failed at the fann@1.0.0 install script 'node-gyp rebuild'.
281 error Make sure you have the latest version of node.js and npm installed.
281 error If you do, this is most likely a problem with the fann package,
281 error not with npm itself.
281 error Tell the author that this fails on your system:
281 error     node-gyp rebuild
281 error You can get information on how to open an issue for this project with:
281 error     npm bugs fann
281 error Or if that isn't available, you can get their info via:
281 error     npm owner ls fann
281 error There is likely additional logging output above.
282 verbose exit [ 1, true ]

**Comment by krystianity** [comment]
that log is most likely not going to help :(

**Comment by formigone** [comment]
I'm having a similar problem installing node-fann. Here's my log:

```
formigone$ npm install --save fann

> fann@1.0.0 install /Users/formigone/rnd/machine-learning/node_modules/fann
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp: Call to 'pkg-config --atleast-version=2.1.0 fann' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/formigone/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.3.0
gyp ERR! command "/Users/formigone/.nvm/versions/node/v6.9.4/bin/node" "/Users/formigone/.nvm/versions/node/v6.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/formigone/rnd/machine-learning/node_modules/fann
gyp ERR! node -v v6.9.4
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN machine-learning@1.0.0 No description
npm WARN machine-learning@1.0.0 No repository field.
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/formigone/.nvm/versions/node/v6.9.4/bin/node" "/Users/formigone/.nvm/versions/node/v6.9.4/bin/npm" "install" "--save" "fann"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! fann@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fann@1.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fann package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fann
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fann
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/formigone/rnd/machine-learning/npm-debug.log
```

I'm on Mac 10.12.2.

|  |  |
|--|--|
Node | v6.9.4
NPM | 3.10.10
pkg-config | 0.29.1
node-gyp | v3.5.0
glib | 2.50.2

Thanks

**Comment by c0d3runn3r** [comment]
Doesn't work for me either.  I've tried Node 7 and Node 8 with multiple versions of node-gyp from the latest (3.6.2) down to 2.0.2.  This is on Debian Jessie.  I've tried the Debian fann libs and also compiling and installing from source.  I suspect that v8 has changed the way they do things and that node-fann needs to be updated to conform. 

```
*** snip ***
../../nan/nan.h: In function ‘v8::Local<v8::Script> NanCompileScript(v8::Local<v8::String>)’:
../../nan/nan.h:717:74: warning: ‘static v8::Local<v8::Script> v8::ScriptCompiler::Compile(v8::Isolate*, v8::ScriptCompiler::Source*, v8::ScriptCompiler::CompileOptions)’ is deprecated (declared at /root/.node-gyp/7.2.1/include/node/v8.h:1319): Use maybe version [-Wdeprecated-declarations]
     return v8::ScriptCompiler::Compile(v8::Isolate::GetCurrent(), &source);
                                                                          ^
../src/fann-accs.cc: In static member function ‘static void NNet::GetWeights(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/fann-accs.cc:303:49: warning: ‘bool v8::Object::Has(uint32_t)’ is deprecated (declared at /root/.node-gyp/7.2.1/include/node/v8.h:2746): Use maybe version [-Wdeprecated-declarations]
     if (!result_object->Has(conns[i].from_neuron)) {
                                                 ^
fann.target.mk:102: recipe for target 'Release/obj.target/fann/src/fann-accs.o' failed
make: *** [Release/obj.target/fann/src/fann-accs.o] Error 1
make: Leaving directory '/shared-jessie/makemap/node_modules/fann/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /shared-jessie/makemap/node_modules/fann
gyp ERR! node -v v7.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN makemap@1.0.0 No description
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "fann"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! fann@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
```
